### ISSUE TITLE
Add "Attendance/Checkin Household" permission

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AttendanceApi#5]
In the list of permissions on AccessApi, add a new one for AttendanceApi of "Attendance/Checkin Household" and update the church init script so this is enabled for the "Everyone" group by default.

Modify the /visits/checkin and get and post methods to allow anyone with this permission to fetch/save their own household only. This is in addition to allowing anyone with the broader "Attendance/Edit" permission to edit anyone.

**Comment by pranavmalvawala** [comment]
There is an update, according to our last chat, we won't be comparing householdIds. Just add the permission check, household restriction will be handled in the mobile app.
